baskets/urls.py
from django.urls import path

from baskets.views import add_to_basket, remove_from_basket, basket_edit

app_name = 'products'

urlpatterns = [
    path('add/<int:product_id>/', add_to_basket, name='add_to_basket'),
    path('add/<int:product_id>/<int:category_id>/', add_to_basket, name='add_to_basket_category'),
    path('remove/<int:id>/', remove_from_basket, name='remove_from_basket'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import IndexView

urlpatterns = [
    path('', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin-staff/', include('admins.urls', namespace='admins')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from orders.views import OrderList, OrderItemCreate, OrderItemUpdate, OrderItemDelete, OrderItemRead, \
    confirm_order_forming, product_price

app_name = 'orders'

urlpatterns = [
    path('', login_required(OrderList.as_view()), name='orders_list'),
    path('create/', login_required(OrderItemCreate.as_view()), name='orders_create'),
    path('<pk>/', login_required(OrderItemRead.as_view()), name='orders_read'),
    path('update/<pk>/', login_required(OrderItemUpdate.as_view()), name='orders_update'),
    path('delete/<pk>/', login_required(OrderItemDelete.as_view()), name='orders_delete'),
    path('confirm/<pk>/', login_required(confirm_order_forming), name='orders_confirm'),
    path('product/<pk>/price/', login_required(product_price), name='product_price'),
]

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from users.views import UserLoginView, UserLogoutView, UserRegisterView, UserProfileUpdateView, verify

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserProfileUpdateView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<email>/<activation_key>/', verify, name='verify'),
]

baskets/models.py
from django.db import models
from django.utils.functional import cached_property

from products.models import Product
from users.models import User


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    @cached_property
    def get_baskets(self):
        return Basket.objects.filter(user=self.user).select_related()

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

    def total_sum(self):
        return sum(basket.sum() for basket in self.get_baskets)

    def total_quantity(self):
        return sum(basket.quantity for basket in self.get_baskets)

    def get_summary(self):
        baskets = self.get_baskets
        return {
            'total_sum': sum(basket.sum() for basket in baskets),
            'total_quantity': sum(basket.quantity for basket in baskets),
        }

baskets/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import JsonResponse
from django.shortcuts import HttpResponseRedirect
from django.template.loader import render_to_string

from baskets.models import Basket
from products.models import Product


@login_required
def add_to_basket(request, product_id, category_id=None):
    if request.is_ajax():
        product = Product.objects.get(id=product_id)
        baskets = Basket.objects.filter(user=request.user, product=product).select_related()

        if not baskets.exists():
            Basket.objects.create(user=request.user, product=product, quantity=1)
        else:
            basket = baskets.first()
            basket.quantity = F('quantity') + 1
            basket.save()

        if category_id:
            products = Product.objects.filter(is_active=True, category_id=category_id).select_related()
        else:
            products = Product.objects.filter(is_active=True).select_related().order_by('price')
        context = {'object_list': products}
        result = render_to_string('products/products_list.html', context, request)
        return JsonResponse({'result': result})


@login_required
def remove_from_basket(request, id):
    Basket.objects.get(id=id).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required()
def basket_edit(request, id, quantity):
    if request.is_ajax():
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            if quantity > basket.quantity:
                basket.quantity = quantity
            elif quantity != basket.quantity:
                basket.quantity = quantity
            basket.save()
        else:
            basket.delete()
        baskets = Basket.objects.filter(user=request.user)
        context = {'baskets': baskets}
        result = render_to_string('baskets/baskets.html', context)
        return JsonResponse({'result': result})

baskets/templates/baskets/baskets.html
<div class="basket-list">
    {% if baskets %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
        </h4>
        {% for basket in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ basket.id }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="0"
                                       max="{{ basket.quantity|add:basket.product.quantity }}">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'baskets:remove_from_basket' basket.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ baskets.0.total_sum }} руб.</h4>
            </div>
        </div>
        <a href="{% url 'orders:orders_create' %}" class="btn btn-success btn-lg float-right">Оформить</a>
    {% else %}
        <h4 class="mt-3 mb-3 text-center">
            Корзина пуста
        </h4>
    {% endif %}
</div>