geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import IndexView

urlpatterns = [
    path('', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin-staff/', include('admins.urls', namespace='admins')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from orders.views import OrderList, OrderItemCreate, OrderItemUpdate, OrderItemDelete, OrderItemRead, \
    confirm_order_forming, product_price

app_name = 'orders'

urlpatterns = [
    path('', login_required(OrderList.as_view()), name='orders_list'),
    path('create/', login_required(OrderItemCreate.as_view()), name='orders_create'),
    path('<pk>/', login_required(OrderItemRead.as_view()), name='orders_read'),
    path('update/<pk>/', login_required(OrderItemUpdate.as_view()), name='orders_update'),
    path('delete/<pk>/', login_required(OrderItemDelete.as_view()), name='orders_delete'),
    path('confirm/<pk>/', login_required(confirm_order_forming), name='orders_confirm'),
    path('product/<pk>/price/', login_required(product_price), name='product_price'),
]

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from users.views import UserLoginView, UserLogoutView, UserRegisterView, UserProfileUpdateView, verify

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserProfileUpdateView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<email>/<activation_key>/', verify, name='verify'),
]

orders/models.py
from django.conf import settings
from django.db import models
from django.utils.functional import cached_property

from products.models import Product


class Order(models.Model):
    FORMING = 'FM'
    PROCEED = 'PRC'
    DELIVERY = 'DLV'
    DONE = 'DN'
    CANCELED = 'CND'

    STATUSES = (
        (FORMING, 'формирование'),
        (PROCEED, 'в обработке'),
        (DELIVERY, 'доставка'),
        (DONE, 'выдан'),
        (CANCELED, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    status = models.CharField(max_length=3, choices=STATUSES, default=FORMING)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(db_index=True, default=True)

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
        ordering = ('-created',)

    def __str__(self):
        return f'Заказ №{self.pk}'

    @cached_property
    def get_items(self):
        return self.orderitems.select_related()

    def get_total_quantity(self):
        return sum(list(map(lambda item: item.quantity, self.get_items)))

    def get_total_cost(self):
        return sum(list(map(lambda item: item.get_product_cost, self.get_items)))

    def get_summary(self):
        items = self.get_items
        return {
            'total_quantity': sum(list(map(lambda item: item.quantity, items))),
            'total_cost': sum(list(map(lambda item: item.get_product_cost, items)))
        }

    def delete(self, using=None, keep_parents=False):
        item_list = self.orderitems.all()
        for item in item_list:
            item.product.quantity += item.quantity
            item.product.save()
        self.is_active = False
        self.status = self.CANCELED
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    @property
    def get_product_cost(self):
        return self.quantity * self.product.price

orders/forms.py
from django import forms

from orders.models import Order, OrderItem


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class OrderItemForm(forms.ModelForm):
    price = forms.CharField(label='цена', required=False)

    class Meta:
        model = OrderItem
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

orders/views.py
from django.db import transaction
from django.db.models.signals import pre_save, pre_delete
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView

from baskets.models import Basket
from orders.forms import OrderItemForm
from orders.models import Order, OrderItem
from products.models import Product


class OrderList(ListView):
    model = Order
    extra_context = {'title': 'Список заказов'}

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class OrderItemCreate(CreateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:orders_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        OrderFormset = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.method == 'POST':
            formset = OrderFormset(self.request.POST)
        else:
            basket_items = Basket.objects.filter(user=self.request.user).select_related()
            if basket_items.exists():
                OrderFormset = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=basket_items.count())
                formset = OrderFormset()
                for num, form in enumerate(formset.forms):
                    form.initial['product'] = basket_items[num].product
                    form.initial['quantity'] = basket_items[num].quantity
                    form.initial['price'] = basket_items[num].product.price
            else:
                formset = OrderFormset()

        context['orderitems'] = formset
        context['title'] = 'Создание заказа'
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            user = self.request.user
            form.instance.user = user
            Basket.objects.filter(user=user).delete()
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        return super().form_valid(form)


class OrderItemRead(DetailView):
    model = Order
    extra_context = {'title': 'Детали заказа'}


class OrderItemUpdate(UpdateView):
    model = Order
    fields = []
    success_url = reverse_lazy('orders:orders_list')
    extra_context = {'title': 'Редактирование заказа'}

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        OrderFormset = inlineformset_factory(Order, OrderItem, form=OrderItemForm, extra=1)

        if self.request.method == 'POST':
            formset = OrderFormset(self.request.POST, instance=self.object)
        else:
            queryset = self.object.orderitems.select_related()
            formset = OrderFormset(instance=self.object, queryset=queryset)
            for form in formset.forms:
                if form.instance.pk:
                    form.initial['price'] = form.instance.product.price

        data['orderitems'] = formset
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        orderitems = context['orderitems']

        with transaction.atomic():
            form.instance.user = self.request.user
            self.object = form.save()
            if orderitems.is_valid():
                orderitems.instance = self.object
                orderitems.save()

        return super().form_valid(form)


class OrderItemDelete(DeleteView):
    model = Order
    success_url = reverse_lazy('orders:orders_list')
    extra_context = {'title': 'Удаление заказа'}


def confirm_order_forming(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = Order.PROCEED
    order.save()
    return HttpResponseRedirect(reverse('orders:orders_list'))


@receiver(pre_save, sender=OrderItem)
@receiver(pre_save, sender=Basket)
def product_quantity_update_on_save(sender, update_fields, instance, **kwargs):
    if instance.pk:
        instance.product.quantity -= instance.quantity - sender.objects.get(pk=instance.pk).quantity
    else:
        instance.product.quantity -= instance.quantity
    instance.product.save()


@receiver(pre_delete, sender=OrderItem)
@receiver(pre_delete, sender=Basket)
def product_quantity_update_on_delete(sender, instance, **kwargs):
    instance.product.quantity += instance.quantity
    instance.product.save()


def product_price(request, pk):
    if request.is_ajax():
        product_item = Product.objects.filter(pk=pk).first()
        if product_item:
            return JsonResponse({'price': product_item.price, 'quantity': product_item.quantity})
        return JsonResponse({'price': 0})

orders/templates/orders/order_confirm_delete.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/orders.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="category_delete">
            <div class="h1">Уверены, что хотите удалить?</div>
            {% include 'orders/includes/inc_order_summary.html' %}
            <div class="row">
                <form action="{% url 'orders:orders_delete' object.pk %}" method="post">
                    {% csrf_token %}
                    <input class="btn-lg btn-danger" type="submit" value="удалить">
                </form>
                <a href="{% url 'orders:orders_list' %}" class="btn-lg btn-success ml-5">отмена</a>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/orders.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container mt-3">
        {% include 'orders/includes/inc_order_summary.html' %}
        <div class="basket_list">
            {% for item in object.get_items %}
                <div class="list-group-item">
                    <span>{{ item.product.category.name }}</span>
                    <span>{{ item.product.name }}</span>
                    <span>{{ item.product.price }}&nbspруб</span>
                    <span>x {{ item.quantity }} шт.</span>
                    <span>= {{ item.get_product_cost }}&nbspруб</span>
                </div>
            {% endfor %}
        </div>
        {% include 'orders/includes/inc_order_actions.html' %}
    </div>
{% endblock %}

orders/templates/orders/order_form.html
{% extends 'products/base.html' %}
{% load static %}
{% load cache %}

{% block css %}
    <link href="{% static 'css/orders.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container mt-3">
        {% include 'orders/includes/inc_order_summary.html' %}
        <form action="" name="order_form" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th>
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr name="formset_row">
                        {% for field in form.visible_fields %}
                            <td>
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name != 'price' %}
                                    {% if field.name == 'product' %}
                                        {% cache 3600 orderitemform_product field.value %}
                                            {{ field }}
                                        {% endcache %}
                                    {% endif %}
                                {% endif %}
                                {% if field.name == 'price' %}
                                    {% if field.value %}
                                        <span class="orderitems-{{ forloop.parentloop.counter0 }}-price">{{ field.value }} руб.</span>
                                    {% endif %}
                                {% elif field.name == 'quantity' and field.value %}
                                    <input type="number"
                                           name="orderitems-{{ forloop.parentloop.counter0 }}-quantity"
                                           value="{{ field.value }}" min="0" max="{{ form.instance.product.quantity }}"
                                           class="form-control">
                                {% elif field.name == 'quantity' %}
                                    <input type="number"
                                           name="orderitems-{{ forloop.parentloop.counter0 }}-quantity"
                                           value="0" min="0" max="{{ form.instance.product.quantity }}"
                                           class="form-control">
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <button type="submit" value="сохранить" class="btn btn-primary btn-round form-control">сохранить
            </button>
            {% include 'orders/includes/inc_order_actions.html' %}
        </form>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'js/orders-scripts.js' %}"></script>
    <script src="{% static 'vendor/jquery/jquery.formset.js' %}"></script>
{% endblock %}

orders/templates/orders/order_list.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'css/orders.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="h2 text-center head">
            Ваши заказы,
            {% if user.first_name %}
                {{ user.first_name|title }}
            {% else %}
                Пользователь
            {% endif %}
        </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Создан</th>
                <th scope="col">Обновлен</th>
                <th scope="col">Статус</th>
            </tr>
            </thead>
            <tbody>
            {% for item in object_list %}
                {% if item.is_active %}
                    <tr>
                        <th scope="row">{{ item.pk }}</th>
                        <td>{{ item.created|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.updated|date:"Y-m-d H:i:s" }}</td>
                        <td>{{ item.get_status_display }}</td>
                        <td>
                            <a href="{% url 'orders:orders_read' item.pk %}" class="btn btn-outline-primary">
                                посмотреть
                            </a>
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'orders:orders_update' item.pk %}" class="btn btn-outline-info">
                                    редактировать
                                </a>
                            {% endif %}
                        </td>
                        <td>
                            {% if item.status == 'FM' %}
                                <a href="{% url 'orders:orders_delete' item.pk %}" class="btn btn-outline-danger">
                                    удалить
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <button class="btn btn-default btn-round">
            <a href="{% url 'orders:orders_create' %}" class="btn btn-outline-success">
                новый заказ
            </a>
        </button>
    </div>
{% endblock %}