admins/urls.py
from django.urls import path

from admins.views import AdminIndexView, AdminUserListView, AdminUserCreateView, AdminUserUpdateView, \
    AdminUserDeleteView, AdminUserCompleteDeleteView, AdminProductListView, AdminProductCreateView, \
    AdminProductUpdateView, AdminProductDeleteView, AdminProductCompleteDeleteView, AdminOrderListView, \
    AdminProductCategoryListView, AdminProductCategoryCreateView, AdminProductCategoryUpdateView, \
    AdminCategoryDeleteView, update_order_status, cancel_order, change_product_is_active_status, \
    change_productcategory_is_active_status, change_user_is_active_status, change_user_is_staff_status

app_name = 'admins'

urlpatterns = [
    path('', AdminIndexView.as_view(), name='index'),
    path('users', AdminUserListView.as_view(), name='admin_users'),
    path('users/create/', AdminUserCreateView.as_view(), name='admin_users_create'),
    path('users/update/<int:pk>', AdminUserUpdateView.as_view(), name='admin_users_update'),
    path('users/update-status/<int:pk>', change_user_is_active_status, name='admin_users_update_status'),
    path('users/update-staff-status/<int:pk>', change_user_is_staff_status, name='admin_users_update_staff_status'),
    path('users/delete/<int:pk>', AdminUserDeleteView.as_view(), name='admin_users_delete'),
    path('users/complete-delete/<int:pk>', AdminUserCompleteDeleteView.as_view(), name='admin_users_complete_delete'),
    path('category', AdminProductCategoryListView.as_view(), name='admin_category'),
    path('category/create/', AdminProductCategoryCreateView.as_view(), name='admin_category_create'),
    path('category/update/<int:pk>', AdminProductCategoryUpdateView.as_view(), name='admin_category_update'),
    path('category/update-status/<int:pk>', change_productcategory_is_active_status,
         name='admin_category_update_status'),
    path('category/delete/<int:pk>', AdminCategoryDeleteView.as_view(), name='admin_category_delete'),
    path('products', AdminProductListView.as_view(), name='admin_products'),
    path('products/category/<int:pk>', AdminProductListView.as_view(), name='admin_products_category'),
    path('products/create/', AdminProductCreateView.as_view(), name='admin_products_create'),
    path('products/update/<int:pk>', AdminProductUpdateView.as_view(), name='admin_products_update'),
    path('products/update-status/<int:pk>', change_product_is_active_status, name='admin_products_update_status'),
    path('products/delete/<int:pk>', AdminProductDeleteView.as_view(), name='admin_products_delete'),
    path('products/complete-delete/<int:pk>', AdminProductCompleteDeleteView.as_view(),
         name='admin_products_complete_delete'),
    path('orders/', AdminOrderListView.as_view(), name='admin_orders'),
    path('orders/delete/<pk>', cancel_order, name='admin_orders_delete'),
    path('update_order_status/<pk>', update_order_status, name='update_order_status'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import IndexView

urlpatterns = [
    path('', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('admin-staff/', include('admins.urls', namespace='admins')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from users.views import UserLoginView, UserLogoutView, UserRegisterView, UserProfileUpdateView, verify

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    path('profile/', UserProfileUpdateView.as_view(), name='profile'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('verify/<email>/<activation_key>/', verify, name='verify'),
]

orders/models.py
from django.conf import settings
from django.db import models
from django.utils.functional import cached_property

from products.models import Product


class Order(models.Model):
    FORMING = 'FM'
    PROCEED = 'PRC'
    DELIVERY = 'DLV'
    DONE = 'DN'
    CANCELED = 'CND'

    STATUSES = (
        (FORMING, 'формирование'),
        (PROCEED, 'в обработке'),
        (DELIVERY, 'доставка'),
        (DONE, 'выдан'),
        (CANCELED, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    status = models.CharField(max_length=3, choices=STATUSES, default=FORMING)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(db_index=True, default=True)

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'
        ordering = ('-created',)

    def __str__(self):
        return f'Заказ №{self.pk}'

    @cached_property
    def get_items(self):
        return self.orderitems.select_related()

    def get_total_quantity(self):
        return sum(list(map(lambda item: item.quantity, self.get_items)))

    def get_total_cost(self):
        return sum(list(map(lambda item: item.get_product_cost, self.get_items)))

    def get_summary(self):
        items = self.get_items
        return {
            'total_quantity': sum(list(map(lambda item: item.quantity, items))),
            'total_cost': sum(list(map(lambda item: item.get_product_cost, items)))
        }

    def delete(self, using=None, keep_parents=False):
        item_list = self.orderitems.all()
        for item in item_list:
            item.product.quantity += item.quantity
            item.product.save()
        self.is_active = False
        self.status = self.CANCELED
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitems')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

    @property
    def get_product_cost(self):
        return self.quantity * self.product.price

admins/templates/admins/admin-category-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Продукты</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Продукты
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Название</th>
                                <th>Описание</th>
                                <th>Активный</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Название</th>
                                <th>Описание</th>
                                <th>Активный</th>
                                <th></th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for category in object_list %}
                                <tr>
                                    <td>{{ category.id }}</td>
                                    <td><a href="{% url 'admins:admin_category_update' category.id %}"
                                           style="color: dodgerblue">{{ category.name }}</a></td>
                                    <td>{{ category.description }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'admins:admin_category_update_status' category.pk %}">
                                            <i class="{% if category.is_active %}
                                                          fas fa-check-circle
                                                      {% else %}
                                                          fas fa-times-circle
                                                      {% endif %}"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'admins:admin_products_category' category.id %}"
                                           class="btn btn-outline-primary col">
                                            Список продуктов в категории
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:admin_category_create' %}">
                        <button class="btn btn-success">Создать категорию</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admins/templates/admins/admin-orders-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Заказы</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Заказы
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Пользователь</th>
                                <th>Создан</th>
                                <th>Обновлен</th>
                                <th class="text-center">Статус - нажмите для обновления</th>
                                <th class="text-center">Отменить заказ</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Пользователь</th>
                                <th>Создан</th>
                                <th>Обновлен</th>
                                <th class="text-center">Статус - нажмите для обновления</th>
                                <th class="text-center">Отменить заказ</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for order in object_list %}
                                <tr>
                                    <td>{{ order.id }}</td>
                                    <td>{{ order.user.username }}</td>
                                    <td>{{ order.created }}</td>
                                    <td>{{ order.updated }}</td>
                                    <td><a href="{% url 'admins:update_order_status' order.pk %}"
                                           class="btn btn-outline-primary col">{{ order.get_status_display }}</a></td>
                                    {% if order.status == 'CND' or order.status == 'DN' %}
                                        <td></td>
                                    {% else %}
                                        <td><a href="{% url 'admins:admin_orders_delete' order.pk %}"
                                               class="btn btn-outline-primary col">Отменить</a></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admins/templates/admins/admin-products-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Продукты</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Продукты
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Название</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Категория</th>
                                <th>Активный</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Название</th>
                                <th>Цена</th>
                                <th>Количество</th>
                                <th>Категория</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for product in object_list %}
                                <tr>
                                    <td><a href="{% url 'admins:admin_products_update' product.id %}"
                                           style="color: dodgerblue">{{ product.name }}</a></td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ product.quantity }}</td>
                                    <td>{{ product.category }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'admins:admin_products_update_status' product.pk %}">
                                            <i class="{% if product.is_active %}
                                                          fas fa-check-circle
                                                      {% else %}
                                                          fas fa-times-circle
                                                      {% endif %}"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:admin_products_create' %}">
                        <button class="btn btn-success">Создать продукт</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admins/templates/admins/admin-products-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование продукта</h1>
            <div class="card-body">
                <form action="{% url 'admins:admin_products_update' product.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.name.id_for_label }}">Название</label>
                                {{ form.name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.category.id_for_label }}">Категория</label>
                                {{ form.category }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.price.id_for_label }}">Цена</label>
                            {{ form.price }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.quantity.id_for_label }}">
                                Количество
                            </label>
                            {{ form.quantity }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12">
                            <label class="small mb-1" for="{{ form.description.id_for_label }}">Описание</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <form action="{% url 'admins:admin_products_delete' product.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit"
                                   value="{% if product.is_active %} Удалить {% else %} Восстановить {% endif %}"
                                   class="btn btn-block {% if product.is_active %} btn-warning {% else %} btn-success {% endif %}">
                        </form>
                        <form action="{% url 'admins:admin_products_complete_delete' product.id %}" method="post"
                              class="mt-2">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger btn-block" value="Удалить из базы данных">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admins/templates/admins/admin-users-read.html
{% extends 'admins/base.html' %}

{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Пользователи</h1>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table mr-1"></i>
                    Пользователи
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Имя</th>
                                <th>Фамилия</th>
                                <th>Адрес эл. почты</th>
                                <th>Персонал сайта</th>
                                <th>Активный</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            {% for user in object_list %}
                                <tr>
                                    <td><a href="{% url 'admins:admin_users_update' user.id %}"
                                           style="color: dodgerblue">{{ user.username }}</a></td>
                                    <td>{{ user.first_name }}</td>
                                    <td>{{ user.last_name }}</td>
                                    <td>{{ user.email }}</td>
                                    <td class="text-center">
                                        <a href="{% url 'admins:admin_users_update_staff_status' user.pk %}">
                                            <i class="{% if user.is_staff %}
                                                          fas fa-check-circle
                                                      {% else %}
                                                          fas fa-times-circle
                                                      {% endif %}"></i>
                                        </a>
                                    </td>
                                    <td class="text-center">
                                        <a href="{% url 'admins:admin_users_update_status' user.pk %}">
                                            <i class="{% if user.is_active %}
                                                          fas fa-check-circle
                                                      {% else %}
                                                          fas fa-times-circle
                                                      {% endif %}"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{% url 'admins:admin_users_create' %}">
                        <button class="btn btn-success">Создать пользователя</button>
                    </a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admins/templates/admins/admin-users-update-delete.html
{% extends 'admins/base.html' %}
{% block content %}
    <main>
        <div class="container-fluid">
            <h1 class="mt-4">Редактирование пользователя | {{ user.username }}</h1>
            <div class="card-body">
                <form action="{% url 'admins:admin_users_update' user.id %}" method="post"
                      enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите
                                    изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <form action="{% url 'admins:admin_users_delete' user.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit"
                                   value="{% if user.is_active %} Удалить {% else %} Восстановить {% endif %}"
                                   class="btn btn-block {% if user.is_active %} btn-warning {% else %} btn-success {% endif %}">
                        </form>
                        <form action="{% url 'admins:admin_users_complete_delete' user.id %}" method="post"
                              class="mt-2">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-danger btn-block" value="Удалить из базы данных">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

admins/templates/admins/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
          crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
    </button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Поиск..." aria-label="Search"
                   aria-describedby="basic-addon2"/>
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </div>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Приложения</div>
                    <a class="nav-link" href="{% url 'admins:admin_users' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-users"></i>
                        </div>
                        Пользователи
                    </a>
                    <a class="nav-link" href="{% url 'admins:admin_orders' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-shopping-basket"></i>
                        </div>
                        Заказы
                    </a>
                    <a class="nav-link" href="{% url 'admins:admin_products' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-tshirt"></i>
                        </div>
                        Продукты
                    </a>
                    <a class="nav-link" href="{% url 'admins:admin_category' %}">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-filter"></i>
                        </div>
                        Категории
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer"></div>
        </nav>
    </div>
    <div id="layoutSidenav_content">
        {% block content %}
        {% endblock %}
        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid">
                <div class="d-flex align-items-center justify-content-between small">
                    <div class="text-muted">Copyright &copy; GeekShop {% now 'Y' %}</div>
                </div>
            </div>
        </footer>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="{% static 'js/datatable.js' %}"></script>
</body>
</html>